FROM redis:6.2

USER root

RUN groupadd -r redisgroup && \
    useradd -r -g redisgroup -m -s /bin/bash redisuser

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Stay as root so the entrypoint can do chown
EXPOSE 6379
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["redis-server"]
