services:
  postgres:
    image: postgres:17
    container_name: sciarticle-db
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb/init-django-user.sql:/docker-entrypoint-initdb.d/init-django-user.sql
    networks:
      - bot

  redis:
    image: redis:7-alpine
    container_name: sciarticle_cache
    restart: always
    env_file:
      - ../.env
    ports:
      - "6379:6379"
    networks:
      - bot

  celery:
    build:
      context: ..
      dockerfile: infra/Dockerfile.celery
    container_name: celery_worker
    restart: always
    depends_on:
      - redis
      - postgres
    env_file:
      - ../.env
    environment:
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=sciarticle.settings
    volumes:
      - ..:/app
    working_dir: /app/src
    command: ["poetry", "run", "celery", "-A", "src.celery_app", "worker", "--loglevel=info"]
    networks:
      - bot

  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile.celery
    container_name: sciarticle-web
    restart: always
    env_file:
      - ../.env
    environment:
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=sciarticle.settings
      - DB_HOST=postgres
      - DB_PORT=5432
    working_dir: /app/src
    volumes:
      - ..:/app
    command: >
      sh -c "
        poetry run python manage.py makemigrations --noinput &&
        poetry run python manage.py migrate --noinput &&
        poetry run python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - bot

  bot:
    build:
      context: ..
      dockerfile: infra/Dockerfile.celery
    container_name: sciarticle-bot
    restart: always
    env_file:
      - ../.env
    environment:
    - PYTHONPATH=/app
    - DJANGO_SETTINGS_MODULE=sciarticle.settings
    working_dir: /app/src
    volumes:
      - ..:/app
    command: [ "poetry", "run", "python", "bot/bot.py" ]
    depends_on:
      - redis
      - postgres
    networks:
      - bot

networks:
  bot:
    driver: bridge

volumes:
  postgres_data: