version: '3.8'

services:
  # Redis service
  redis:
    image: redis:6.2
    container_name: redis_sciarticle
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # PostgreSQL service
  db:
    image: postgres:14
    container_name: postgres_sciarticle
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Celery Worker
  celery_worker:
    # Adjust the context and dockerfile paths to your project
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: sciarticle_celery_worker
    command: "celery -A src.celery_app worker --loglevel=info"
    env_file:
      - ../.env
    volumes:
      - ../:/app
    depends_on:
      - redis
      - db

  # Celery Beat for periodic tasks
  celery_beat:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: sciarticle_celery_beat
    command: "celery -A src.celery_app beat --loglevel=info"
    env_file:
      - ../.env
    volumes:
      - ../:/app
    depends_on:
      - redis
      - db

volumes:
  redis_data:
  postgres_data:
