services:
  postgres:
    image: postgres:17
    container_name: sciarticle-db
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot

  redis:
    image: redis:7-alpine
    container_name: sciarticle_cache
    restart: always
    env_file:
      - ../.env
    ports:
      - "6379:6379"
    networks:
      - bot

  celery:
    build:
      context: ..
      dockerfile: infra/Dockerfile.celery
    container_name: celery_worker
    restart: always
    depends_on:
      - redis
      - postgres
    env_file:
      - ../.env
    volumes:
      - ..:/app
    working_dir: /app
    command: ["poetry", "run", "celery", "-A", "src.celery_app", "worker", "--loglevel=info"]
    networks:
      - bot

volumes:
  postgres_data:

networks:
  bot:
