# Generated by Django 5.2 on 2025-04-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_chatuser_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_message_id',
            field=models.IntegerField(default=1, help_text='Telegram message_id, в ответ на которое пользователь делал /request'),
            preserve_default=False,
        ),
    ]
