# Generated by Django 5.2 on 2025-04-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_request_request_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_message_id',
            field=models.BigIntegerField(help_text='Telegram message_id, в ответ на которое пользователь делал /request'),
        ),
    ]
