# Generated by Django 5.2 on 2025-05-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_request_request_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='request_message_id',
        ),
        migrations.AddField(
            model_name='request',
            name='message_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='doi',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('expired', 'expired'), ('removed', 'removed')], max_length=25),
        ),
    ]
